services:
  wire-node:
    container_name: wire-node
    build: ./wire
    image: wire-node
    volumes:
      - ./wire/data/:/nodeos/wire/data/ 
      - ./wire/config/:/nodeos/wire/config/
    network_mode: "host"
    # ports:
    #   # - "9000:9000"  # Leap bootstrap peering nodes - eosio
    #   # - "9001:9001"  # Leap bootstrap peering nodes - producer111a
    #   # - "9002:9002"  # Leap bootstrap peering nodes - producer111b
    #   # - "9003:9003"  # Leap bootstrap peering nodes - producer111c
    #   - "8888:8888"  # External port for HTTP API requests
    #   - "8080:8080"  # External port for state history plugin API
    #   - "4444:4444"  # Mapped P2P network port
    #   - "4443:4443"  # Additional mapped port for other services
    # networks:
    #   - hyperion
    command: nodeos --genesis-json /nodeos/wire/config/genesis.json --disable-replay-opts --data-dir /nodeos/wire/data --config-dir /nodeos/wire/config --delete-all-blocks # Command to run nodeos

networks:
  hyperion:
    external: true