services:
  wire-node:
    container_name: wire-node
    build: ./wire
    image: wire-node
    volumes:
      - ./wire/data/:/nodeop/wire/data/ 
      - ./wire/config/:/nodeop/wire/config/
    network_mode: "host"
    command: nodeop --genesis-json /nodeop/wire/config/genesis.json --data-dir /nodeop/wire/data --config-dir /nodeop/wire/config --disable-replay-opts # Command to run nodeop

networks:
  hyperion:
    external: true