services:
  indexer:
    build:
      context: ../../
      dockerfile: hyperion-docker-new/hyperion/Dockerfile
    volumes:
      - ./config/connections.json:/hyperion-history-api/connections.json
      - ./config/chains/:/hyperion-history-api/chains/
    networks:
      - hyperion
    command: ./run.sh wire-indexer

  api:
    build:
      context: ../../
      dockerfile: hyperion-docker-new/hyperion/Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - indexer
    volumes:
      - ./config/connections.json:/hyperion-history-api/connections.json
      - ./config/chains/:/hyperion-history-api/chains/
    networks:
      - hyperion
    command: ./run.sh wire-api

networks:
  hyperion:
    external: true